# Generated by Django 3.1.4 on 2020-12-23 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ubicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoFactura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Reparacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=200)),
                ('telefono', models.IntegerField()),
                ('direccion', models.CharField(max_length=255)),
                ('recepcion', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('marca', models.CharField(blank=True, max_length=255, null=True)),
                ('factura', models.FileField(blank=True, null=True, upload_to='facturas/')),
                ('modelo', models.CharField(blank=True, max_length=255, null=True)),
                ('falla', models.TextField()),
                ('observacion', models.TextField()),
                ('nombre_cliente', models.CharField(max_length=255)),
                ('firma_tecnico', models.ImageField(upload_to='firma/')),
                ('firma_cliente', models.ImageField(upload_to='firma/')),
                ('ordendoc', models.FileField(blank=True, null=True, upload_to='orden/')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorAsignado', to=settings.AUTH_USER_MODEL)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubicacion.ciudad')),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubicacion.comuna')),
                ('factura_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordentrabajo.estadofactura')),
                ('reparacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordentrabajo.reparacion')),
                ('tecnico', models.ManyToManyField(related_name='tecnicosAsignados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
