# Generated by Django 3.1.5 on 2021-01-15 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordentrabajo', '0002_auto_20210112_0037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='ordendoc',
        ),
    ]
